DROP DATABASE IF EXISTS dbProject;

CREATE DATABASE dbProject;
USE dbProject;

CREATE TABLE Forum(
	forumID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	forumName NVARCHAR(256) NOT NULL,
	shortName NVARCHAR(30) NOT NULL,
	userID INT NOT NULL,
	-- FOREIGN KEY (userID) REFERENCES User(userID)
);

CREATE TABLE Post(
	postID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dateCreated TIMESTAMP NOT NULL,
	likes INT NOT NULL,
	dislikes INT NOT NULL,
	forumID INT NOT NULL,

	isApproved BOOL NOT NULL DEFAULT FALSE,
	isDeleted BOOL NOT NULL DEFAULT FALSE,
	isEdited BOOL NOT NULL DEFAULT FALSE,
	isHighlighted BOOL NOT NULL DEFAULT FALSE,
	isSpam BOOL NOT NULL DEFAULT FALSE,

	message TEXT NOT NULL,
	userID INT NOT NULL,
	-- What??
	parentID INT NOT NULL ,
	points INT NOT NULL,
	threadID INT NOT NULL,
	FOREIGN KEY(parentID) REFERENCES Post(postID)
);

CREATE TABLE User(
	userID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	about NVARCHAR(256) NOT NULL,
	isAnonymous BOOL NOT NULL DEFAULT FALSE,
	realName NVARCHAR(256) NOT NULL,
	username NVARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL

);

CREATE TABLE Thread(
	threadID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	
	dateCreated TIMESTAMP NOT NULL,
	dislikes INT NOT NULL DEFAULT 0,
	likes INT NOT NULL DEFAULT 0,
	
	isClosed BOOL NOT NULL DEFAULT FALSE,
	isDeleted BOOL NOT NULL DEFAULT FALSE,
-- WHAT??
	points INT NOT NULL DEFAULT 0,
	posts INT NOT NULL DEFAULT 0,

	slug VARCHAR(30) NOT NULL,
	title NVARCHAR(250) NOT NULL,

	user INT NOT NULL,
	message TEXT NOT NULL,

	forumID INT NOT NULL,
	FOREIGN KEY(forumID) REFERENCES Forum(forumID)
);

ALTER TABLE Forum
ADD FOREIGN KEY (userID)
REFERENCES User(userID);

